using Invoxa.Web.Domain;

namespace Invoxa.Web.Data;

public static class SeedData
{
    public static void EnsureSeeded(AppDbContext db)
    {
        if (db.Companies.Any()) return;

        var company = new Company
        {
            Name = "BasMan Technology (Demo)",
            TimeZone = "Asia/Kuwait",
            ApprovalStatus = "Active",
            ApprovedAtUtc = DateTime.UtcNow,
            PlanKey = "Pro",
            InvoiceLimit = 999999,
            ClientLimit = 999999,
            InvoiceTemplateKey = "default_modern",
            TemplateDisplayName = "Default Modern",
            DefaultCurrency = "INR",
            PrimaryColor = "#2563eb",
            TableHeaderColor = "#1d4ed8",
            PdfFontSize = 11,
            PdfTitleStyle = "Bold",
            ShowTerms = true,
            ShowNotes = true,
            ShowPaymentDetails = false,
            CustomColumn1Name = "Item",
            CustomColumn2Name = "Qty",
            CustomColumn3Name = "Unit Price",
            CustomColumn4Name = "Total",
            InvoicePrefix = "INV",
            NextInvoiceNumber = 2,
            TaxEnabled = false,
            TaxPresetKey = "kuwait_vat",
            TaxLabel = "VAT",
            TaxRate = 0m,
            PaymentDetails = "Bank transfer details can be added here.",
            CreatedAtUtc = DateTime.UtcNow,
            ThankYouNote = "Thanks for your business.",
            TermsAndConditions = "Full payment is due upon receipt of this invoice.",
            ReminderDaysBeforeDue = 2,
            AutomationIntervalValue = 1,
            AutomationIntervalUnit = "Minutes",
            OverdueReminderEnabled = true,
            OverdueReminderIntervalValue = 1,
            OverdueReminderIntervalUnit = "Days"
        };

        db.Companies.Add(company);
        db.SaveChanges();

        var client = new Client
        {
            CompanyId = company.Id,
            Name = "John Smith Trading",
            Email = "john@example.com",
            Phone = "+96500000000",
            PortalToken = Guid.NewGuid().ToString("N"),
            CreatedAtUtc = DateTime.UtcNow
        };

        db.Clients.Add(client);
        db.SaveChanges();

        var invoice = new Invoice
        {
            CompanyId = company.Id,
            ClientId = client.Id,
            InvoiceNumber = "INV-0001",
            PublicToken = Guid.NewGuid().ToString("N"),
            IssueDate = DateOnly.FromDateTime(DateTime.UtcNow),
            DueDate = DateOnly.FromDateTime(DateTime.UtcNow.AddDays(7)),
            Status = InvoiceStatus.Unpaid,
            Notes = "Demo invoice generated by Invoxa.",
            PaymentLink = null,
            RecurrenceEnabled = false,
            IsRecurringTemplate = false,
            CreatedAtUtc = DateTime.UtcNow
        };

        invoice.Items.Add(new InvoiceItem
        {
            Description = "Automation setup",
            Quantity = 1,
            UnitPrice = 199m
        });

        db.Invoices.Add(invoice);
        db.SaveChanges();

        db.UserAccounts.Add(new UserAccount
        {
            CompanyId = company.Id,
            FullName = "Admin",
            Email = "admin@invoxa.local",
            PasswordHash = Invoxa.Web.Services.PasswordHasher.Hash("Admin@123"),
            Role = "SuperAdmin",
            IsActive = true,
            CreatedAtUtc = DateTime.UtcNow
        });


db.EmailTemplates.AddRange(
    new EmailTemplate
    {
        CompanyId = company.Id,
        TemplateKey = "InvoiceSent",
        Subject = "Invoice {{InvoiceNumber}} from {{CompanyName}}",
        Body = "Hello {{ClientName}},\n\nYour invoice {{InvoiceNumber}} for {{Amount}} is ready.\nDue date: {{DueDate}}\n\nPay here: {{PayNowLink}}\nView invoice: {{ViewInvoiceLink}}\n\nThanks,\n{{CompanyName}}"
    },
    new EmailTemplate
    {
        CompanyId = company.Id,
        TemplateKey = "UpcomingDue",
        Subject = "Reminder: invoice {{InvoiceNumber}} due on {{DueDate}}",
        Body = "Hello {{ClientName}},\n\nThis is a friendly reminder that invoice {{InvoiceNumber}} for {{Amount}} is due on {{DueDate}}.\n\nPay here: {{PayNowLink}}\n\nThanks,\n{{CompanyName}}"
    },
    new EmailTemplate
    {
        CompanyId = company.Id,
        TemplateKey = "DueToday",
        Subject = "Due today: invoice {{InvoiceNumber}}",
        Body = "Hello {{ClientName}},\n\nInvoice {{InvoiceNumber}} for {{Amount}} is due today.\n\nPay here: {{PayNowLink}}\n\nThanks,\n{{CompanyName}}"
    },
    new EmailTemplate
    {
        CompanyId = company.Id,
        TemplateKey = "Overdue",
        Subject = "Overdue: invoice {{InvoiceNumber}}",
        Body = "Hello {{ClientName}},\n\nInvoice {{InvoiceNumber}} for {{Amount}} is overdue. Original due date: {{DueDate}}.\n\nPay here: {{PayNowLink}}\n\nThanks,\n{{CompanyName}}"
    },
    new EmailTemplate
    {
        CompanyId = company.Id,
        TemplateKey = "PaymentReceived",
        Subject = "Payment received for invoice {{InvoiceNumber}}",
        Body = "Hello {{ClientName}},\n\nWe have received your payment for invoice {{InvoiceNumber}}. Amount: {{Amount}}.\n\nThanks,\n{{CompanyName}}"
    }
);
db.SaveChanges();

        db.ReminderLogs.Add(new ReminderLog
        {
            CompanyId = company.Id,
            InvoiceId = invoice.Id,
            Actor = "System",
            Channel = "System",
            Type = "Seeded",
            To = invoice.InvoiceNumber,
            Notes = "Initial demo data created."
        });
        db.SaveChanges();
    }
}
